name: Lint
on: pull_request

jobs:
  run_lint:
    name: Run Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.7"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Install
        run: make install

      - name: Run linting
        run: make lint
